name: Enforce Conventional Commits

on:
  - push
  - pull_request

jobs:
  build:
    name: Validate Commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webiny/action-conventional-commits@v1.3.0
