name: "Lint"
on:
    - push
    - pull_request

jobs:
    install:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v3
              with:
                  version: 8
                  run_install: |
                      - recursive: true
            - name: Lint
              run: pnpm lint
