name: Deploy Documentation Preview on Netlify

on: pull_request

jobs:
  Documentation-Preview:
    name: Deploy Preview on Netlify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: |
            - recursive: true

      - name: Build docs
        run: pnpm build:docs

      - name: Publish docs
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=dist/docs
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      # add a comment to the PR with a link to the preview URL
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'This is a test'
            })
