name: "Publish"
on: push

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: pnpm build

  # npm-publish:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Publish
  #       run: pnpm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  release-publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Publish
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
