name: "Publish"

on:
  push:
    branches:
      - "main"

jobs:
  Create-GitHub-Release:
    name: "Bump Version on master"
    runs-on: ubuntu-latest

    steps:
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          default: prerelease
          tag-prefix: "v"
