name: "Publish"

on:
  push:
    branches:
      - "main"

jobs:
  GitHub-Release:
    name: "Release GitHub Version"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          release-type: node

  # implicitly deploys to unpkg as our cdn
  NPM-Release:
    name: "Release GitHub Version"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
        with:
          ref: ${{ github.ref }}

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@hudson-newey"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: "Install pnpm"
        uses: "pnpm/action-setup@v3"
        with:
          version: 8
          run_install: |
            - recursive: true

      - name: "Publish"
        run: pnpm publish:components
