name: Publish

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string

jobs:
  Publish-Assets:
    name: Publish Assets to NPM and GitHub
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # publish to NPM for each release created
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@hudson-newey"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: |
            - recursive: true

      - name: Publish to NPM
        run: pnpm publish:components

      - name: Publish to GitHub Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          mkdir -p ./dist
          zip -r ./dist/components.zip ./js/ -x "**/node_modules/*"
          gh release upload ${{ inputs.tag_name }} ./dist/components.zip
          gh release upload ${{ inputs.tag_name }} ./js/components.js

  Publish-Documentation:
    name: Publish Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: |
            - recursive: true

      - name: Build docs
        run: pnpm build:docs

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: "./dist/docs"
          production-branch: main
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-deployment-environment: "Documentation"
          enable-github-deployment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
