name: Release

on:
  push:
    branches:
      - main

jobs:
  Create-Release:
    name: Create Release request
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json

      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Publish release
        if: ${{ steps.release.outputs.release_created }}
        uses: ./.github/workflows/publish
        with:
          tag_name: ${{ steps.release.outputs.tag_name }}
