name: "Release"

on:
  push:
    branches:
      - "main"

jobs:
  Create-Release:
    name: "Create Release"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json

      - name: Publish release
        if: ${{ steps.release.outputs.release_created }}
        uses: publish.yml
        env:
          TAG_NAME: ${{ steps.release.outputs.tag_name }}
