name: "Test Storybook"
on:
  - push
  - pull_request

jobs:
  Test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: |
            -recursive: true
      - name: Build Storybook
        run: pnpm build:storybook
      - name: Serve Storybook and run tests
        run: |
          pnpm dlx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "pnpm dlx http-server dist/storybook --port 6006 --silent" \
            "pnpm dlx wait-on tcp:6006 && pnpm test:interaction"
